services:
  - type: web
    name: basho-api
    runtime: python
    pythonVersion: 3.12
    plan: starter
    buildCommand: |
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --no-input &&
      python manage.py migrate
    startCommand: gunicorn basho_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12"
